#! /bin/bash -e

if test "$1" = '--help'; then echo "\
Usage:
  $0 [...<npm args>]
  $0 --help

  This is a proxy to npm. We’ll call \`npm shrinkwrap\` afterwards.
"; exit; fi

cd "$(dirname "$0")"/..
npm=node_modules/.bin/npm

set -x
"$npm" $@
"$npm" shrinkwrap --dev
set +x

read \
  -p 'Would you like us to commit the result? [y/n] ' \
  -n 1 \
  reply
echo
if test "$reply" = 'y'; then
  git commit -m '[scripts/npm] Update dependencies' \
    package.json \
    npm-shrinkwrap.json
fi
